name: SEC Filing Monitor

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor-filings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install requests beautifulsoup4 yfinance matplotlib pandas pytz

    - name: Run SEC monitoring script
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py

    - name: Commit updated log files
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add *.txt
        git commit -m "Update SEC logs [skip ci]" || echo "No changes to commit"
        git push
