# .github/workflows/sec_monitor.yml
name: SEC Filing Monitor

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  monitor-filings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 yfinance matplotlib pandas pytz
    
    - name: Run SEC monitoring script
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python test.py
    
    - name: Upload log files (optional)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: monitoring-logs
        path: |
          *.txt
          *.log
        retention-days: 7
